### PR TITLE
Word

### PR DESCRIPTION
**Pull request by takuho24n**

### CODE REVIEW

**Review by aplazand20 — CHANGES_REQUESTED** [review]
One major request, please remove these buttons from the Regular Category because Regular users SHOULD NOT be able to access these routes.
image

Admin's role is to manage, create, edit, and delete:
1. Categories
2. Words
3. Choices

Regular users can only LEARN.
They cannot see the words, choices and delete the categories.

**Comment by aplazand20** [comment]
As you can see here, I am not admin in this page.
Link of this page: http://fels-graduates-01.herokuapp.com/categories
image

So I can only Learn.

**Comment by aplazand20** [comment]
For this problem where you can create word but cannot Edit
image

**Comment by takuho24n** [comment]
One major request, please remove these buttons from the Regular Category because Regular users SHOULD NOT be able to access these routes.

>right now about this regular category page, those edit, delete, words buttons are not showing when regular users login...

**Comment by aplazand20** [comment]
image
User cannot EDIT because there is no **DEF UPDATE** method for Admin Words controller

**Comment by aplazand20** [comment]
> One major request, please remove these buttons from the Regular Category because Regular users SHOULD NOT be able to access these routes.
> 
> > right now about this regular category page, those edit, delete, words buttons are not showing when regular users login...

Yes but in CATEGORY tab, even Admin cannot see Edit, Delete and Words.
You can only see Edit, Delete and Words if you're in MANAGE CATEGORIES tab.

So This is correct and working
image

But no one (not even admin) should see these buttons in the CATEGORY tab
image

**Comment by aplazand20** [comment]
I suggest studying more about the application, and why there is a difference between MANAGE CATEGORIES and CATEGORY as 
email: **framgia@email.com**
password: **password**
Link: http://fels-graduates-01.herokuapp.com/dashboard
image

**Pull request merged**
